USER_PROFILES_JWT_PUBLIC_KEY: app-local.pub
USER_PROFILES_SERVICE_URL: http://localhost:8085

MONGO_SERVER_URL: localhost
MONGO_SERVER_PORT: 27017
MONGO_USERNAME: root
MONGO_PASSWORD: root1

KAFKA_SERVER_URL: localhost:9092
LOG_TO_FILE: false
